# Sample setup macro with no visualization

/run/verbose 1
/tracking/verbose 0
/hits/verbose 0
/grdm/verbose 0

/WCSim/WCgeom HyperK_20perCent

/WCSim/Construct

/WCSim/PMTQEMethod INQEMETHOD

#turn on or off the collection efficiency
/WCSim/PMTCollEff on

# command to choose save or not save the pi0 info 07/03/10 (XQ)
/WCSim/SavePi0 false

#choose the Trigger & Digitizer type (and options)
/DAQ/Digitizer SKI
/DAQ/Trigger INTRIGGER

#grab the other DAQ options (thresholds, timing windows, etc.)
/control/execute $WCSIMVALIDATION/macs/daq.mac

/control/execute $WCSIMVALIDATION/macs/dark/FILETANKDARK.mac

/control/execute $WCSIMVALIDATION/macs/physics/FILEGUN.mac

/Tracking/fractionOpticalPhotonsToDraw 0.0

/WCSimIO/SaveRooTracker 0

## change the name of the output root file, default = wcsim.root
/WCSimIO/RootFile wcsim_hk20_INQEMETHOD_INTRIGGER_FILEGUNTAG_FILEDARKTAG_nINNEVENTS.root

## set a timer running on WCSimRunAction
#/WCSimIO/Timer false

/run/beamOn INNEVENTS
#exit
